Models/Domain/Product.cs
using System.ComponentModel.DataAnnotations;

namespace Razor_EF_CRUD.Models.Domain
{
    public class Product
    {
        [Key]
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
        public string Availability { get; set; }
        public string Category { get; set; }
    }
}

Models/ViewModels/AddProductViewModel.cs
namespace Razor_EF_CRUD.Models.ViewModels
{
    public class AddProductViewModel
    {
        public string Name { get; set; }
        public string Price { get; set; }
        public string Availability { get; set; }
        public string Category { get; set; }
    }
}

Models/ViewModels/EditProductViewModel.cs
namespace Razor_EF_CRUD.Models.ViewModels
{
    public class EditProductViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
        public string Availability { get; set; }
        public string Category { get; set; }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Razor_EF_CRUD.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Razor_EF_CRUD.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Razor_EF_CRUD.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Products/Add.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Razor_EF_CRUD.Data;
using Razor_EF_CRUD.Models.Domain;
using Razor_EF_CRUD.Models.ViewModels;

namespace Razor_EF_CRUD.Pages.Products
{
    public class AddModel : PageModel
    {
        private readonly RazorPagesDemoDbContext dbContext;

        public AddModel(RazorPagesDemoDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        [BindProperty]
        public AddProductViewModel AddProductRequest { get; set; }
        public void OnGet()
        { 
        }
        public void OnPost()
        {
            //Convert ViewModel to DomainModel
            var productDomainModel = new Product
            {
                Name = AddProductRequest.Name,
                Price = AddProductRequest.Price,
                Availability = AddProductRequest.Availability,
                Category = AddProductRequest.Category
            };
            dbContext.Products.Add(productDomainModel);
            //dbcontext.tablename.Add Method
            dbContext.SaveChanges();

            ViewData["Message"] = "Product added Successfully";
        }
    }
}

Pages/Products/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Razor_EF_CRUD.Data;
using Razor_EF_CRUD.Models.ViewModels;

namespace Razor_EF_CRUD.Pages.Products
{
    public class EditModel : PageModel
    {
        private readonly RazorPagesDemoDbContext dbContext;
        [BindProperty]
        public EditProductViewModel EditProductViewModel { get; set; }
        public EditModel(RazorPagesDemoDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public void OnGet(Guid id)
        {
            var product = dbContext.Products.Find(id);
            if (product != null)
            {
                //Convert Domain model to view model
                EditProductViewModel = new EditProductViewModel()
                {
                    Id = product.Id,
                    Name = product.Name,
                    Price = product.Price,
                    Availability = product.Availability,
                    Category = product.Category

                };
            }
            
        }

        public void OnPostUpdate()
        {
            if (EditProductViewModel != null)
            {
                var existingProduct = dbContext.Products.Find(EditProductViewModel.Id);
                if (existingProduct != null)
                {
                    //Convert ViewModel to Domain Model
                    existingProduct.Name = EditProductViewModel.Name;
                    existingProduct.Price = EditProductViewModel.Price;
                    existingProduct.Availability = EditProductViewModel.Availability;
                    existingProduct.Category = EditProductViewModel.Category;
                    dbContext.SaveChanges();
                    ViewData["UpdateMessage"] = "Product Details Updated Successfully";
                }
                
                
            }
        }

        public IActionResult OnPostDelete()
        {
            var existingProduct = dbContext.Products.Find(EditProductViewModel.Id);
            if(existingProduct != null)
            {
                dbContext.Products.Remove(existingProduct);
                dbContext.SaveChanges();
                //ViewData["DeleteMessage"] = "Product Details Updated Successfully";

                return RedirectToPage("/Products/List");
            }
            return Page();
        }
    }
}

Pages/Products/List.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Razor_EF_CRUD.Data;

namespace Razor_EF_CRUD.Pages.Products
{
    public class ListModel : PageModel
    {
        private readonly RazorPagesDemoDbContext dbContext;
        public List<Models.Domain.Product> products { get; set; }
        public ListModel(RazorPagesDemoDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public void OnGet()
        {
            products = dbContext.Products.ToList();
        }
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Pages/Products/Add.cshtml
@page
@model Razor_EF_CRUD.Pages.Products.AddModel
@{
    var message = ViewData["Message"]?.ToString();
}

<form method="post">
<h1 class="mb-3">Add New Product</h1>
@if (!string.IsNullOrWhiteSpace(message))
    {
        <div class="alert alert-success" role="alert">
            @message
        </div>
    }
    <div class="mb-3">
    <label class="form-label">Product Name:</label>
    <input type = "text" class="form-control" asp-for="AddProductRequest.Name"/>
</div>
<div class="mb-3">
    <label class="form-label">Product Price:</label>
    <input type = "text" class="form-control" asp-for="AddProductRequest.Price"/>
</div>
<div class="mb-3">
    <label class="form-label">Product Availability:</label>
    <input type = "text" class="form-control" asp-for="AddProductRequest.Availability"/>
</div>
<div class="mb-3">
    <label class="form-label">Product Category:</label>
    <input type = "text" class="form-control" asp-for="AddProductRequest.Category"/>
</div>
<div class="mb-3">
    <button type="submit" class="btn btn-primary">Save</button>
</div>
</form>

Pages/Products/Edit.cshtml
@page "{id:Guid}"
@model Razor_EF_CRUD.Pages.Products.EditModel
@{
    var updatemessage = ViewData["UpdateMessage"]?.ToString();
}

<!--@{
    var deletemessage = ViewData["DeleteeMessage"]?.ToString();
}-->
<h1 class="mb-3"> Edit Employee</h1>
<form method="post">
@if (!string.IsNullOrWhiteSpace(updatemessage))
    {
        <div class="alert alert-success" role="alert">
            @updatemessage
        </div>
    }
<!--if (!string.IsNullOrWhiteSpace(deletemessage))
   {
       <div class="alert alert-success" role="alert">
           @deletemessage
       </div>
   }-->
<div class="mb-3">
    <label class="form-label">Product Id:</label>
    <input type = "text" class="form-control" asp-for="EditProductViewModel.Id" readonly/>
</div>
<div class="mb-3">
    <label class="form-label">Product Name:</label>
    <input type = "text" class="form-control" asp-for="EditProductViewModel.Name" />
</div>
<div class="mb-3">
    <label class="form-label">Product Price:</label>
    <input type = "text" class="form-control" asp-for="EditProductViewModel.Price" />
</div>
<div class="mb-3">
    <label class="form-label">Product Availability:</label>
    <input type = "text" class="form-control" asp-for="EditProductViewModel.Availability" />
</div>
<div class="mb-3">
    <label class="form-label">Product Category:</label>
    <input type = "text" class="form-control" asp-for="EditProductViewModel.Category" />
</div>
<div class="mb-3 d-flex justify-content-between">
    <button type="submit" class="btn btn-primary" asp-page-handler="Update">
        Update
    </button>
    <button type="submit" class="btn btn-danger" asp-page-handler="Delete">
        Delete
    </button>
</div>

</form>

Pages/Products/List.cshtml
@page
@model Razor_EF_CRUD.Pages.Products.ListModel
@{
}

<h1 class="mb-3">List of Products</h1>

@if (Model.products != null && Model.products.Any()){
    <table class="table">
        <thead>
            <tr>
                <th>Product Id </th>
                <th>Product Name </th>
                <th>Product Price </th>
                <th>Product Availability </th>
                <th>Product Category </th>
                <th> </th>
            </tr>
        </thead>
        <tbody>
            @foreach(var product in Model.products)
            {
                <tr>
                    <td> @product.Id</td>
                    <td> @product.Name</td>
                    <td> @product.Price</td>
                    <td> @product.Availability</td>
                    <td> @product.Category</td>
                    <td>
                        <a href="/Products/Edit/@product.Id" class="btn btn-dark"> Edit </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else{
    <p> No Employees Found</p>
}

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Razor_EF_CRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Razor_EF_CRUD.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Razor_EF_CRUD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Products/List">Products</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Razor_EF_CRUD - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>